language: node_js
node_js:
  - 10 

before_install:
  - npm i -g npm@latest
  - npm install codecov -g

script:
  - yarn test

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

cache: yarn